# This handles all permissions necessary to enable/disable debug mode in admin dogu
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-ces-control.name" . }}-restore-role
  labels:
    {{- include "k8s-ces-control.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - restores
    verbs:
      - update
      - create
      - get
      - list
      - delete